#! /bin/sh
#ifdef __USAGE
#%C    - Compila todos os arquivos do score (nao interrompe se erro)
#
#Use:
#%C
# Arquivo de comandos do shell para compilar modulos do score
# Autor: Leonel Vicente Mota Ivo	-	Data: 23/06/94
#

# Apenas para depuracao
#set -xv

echo Compilando todos os arquivos do diretorio ../srcs...
echo Compilando os diretorios de biblioteca...
ws -d -l 10 -P lib*,*lib -e i ../srcs "CompilaDir @ $*"
if test $? -ne 0
then
  echo "\007\033<Falha na compilacao de alguma biblioteca!\033>"
fi
echo Compilando os outros diretorios...
ws -d -l 10 -P !lib* -P !*lib -P !*src -P !*default -P !*wgt -e i ../srcs "CompilaDir @ $*"
if test $? -ne 0
then
  echo "\007\033<Falha na compilacao de algum diretorio!\033>"
fi
echo Compilando diretorios Photon...
ws -d -l 10 -P *ph, -e i ../srcs "CompilaDirph @ $*"
if test $? -ne 0
then
  echo "\007\033<Falha na compilacao de algum diretorio!\033>"
else
  echo "\007\033<Compilacao Score terminada!\033>"
fi
/score/util/CheckTamBd
